
# If not specified defaults to today +- 3 days.
# Use the date below to reproduce the last Boston Light Swim event forecast.
date:
    start: null  # 2016-8-16 00:00:00
    stop: null  # 2016-8-29 00:00:00

run_name: 'latest'

# Boston harbor.
region:
    bbox: [-71.3, 42.03, -70.57, 42.63]
    crs: 'urn:ogc:def:crs:OGC:1.3:CRS84'

sos_name: 'sea_water_temperature'

cf_names:
    - sea_water_temperature
    - sea_surface_temperature
    - sea_water_potential_temperature
    - equivalent_potential_temperature
    - sea_water_conservative_temperature
    - pseudo_equivalent_potential_temperature

units: 'celsius'

catalogs:
    - http://www.ngdc.noaa.gov/geoportal/csw
    - https://dev-catalog.ioos.us/csw
    - http://geoport.whoi.edu/csw

# See https://raw.githubusercontent.com/OSGeo/Cat-Interop/master/LinkPropertyLookupTable.csv
service_strings:
    opendap:
        - OPeNDAP:OPeNDAP
        - urn:x-esri:specification:ServiceType:odp:url
    sos:
        - urn:x-esri:specification:ServiceType:sos:url