name: IOOS
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - bagit
  - bokeh
  - cartopy
  - cc-plugin-glider
  - cc-plugin-ncei
  - compliance-checker
  - cython
  - descartes
  - easyargs
  - erddapy
  - folium
  - flake8
  - geojson
  - geojsonio
  - geolinks
  - geopandas
  - gridgeo
  - hvplot
  - ioos-tools
  - jupyter
  - matplotlib-base
  - nbdime
  - nc-time-axis
  - nco
  - oceans
  - oct2py
  - palettable
  - phantomjs
  - pocean-core
  - pyoos
  - pyresample
  - pysgrid
  - pytest
  - pyugrid
  - rasterio
  - rise
  - seaborn
  - selenium
  - sensorml2iso
  - siphon
  - sympy
  - thredds_crawler
  - tqdm
  - utide
  - windrose
  - xarray
  - xlrd
  - xmltodict
