name: IOOS2
channels:
  - conda-forge
  - defaults
dependencies:
  - python=2.7
  - bagit
  - beautifulsoup4
  - bokeh
  - cartopy
  - cc-plugin-glider
  - cmocean
  - compliance-checker
  - ctd
  - cython
  - descartes
  - fiona
  - flake8
  - folium
  - gdal
  - geojson
  - geojsonio
  - geolinks
  - geopandas
  - geos
  - gridgeo
  - gsw
  - iris>=1.12
  - jsanimation
  - jupyter
  - jupyter_contrib_nbextensions
  - matplotlib
  - mpld3
  - mplleaflet
  - nb_conda_kernels
  - nbdime
  - netcdf4
  - numpy
  - oceans
  - oct2py
  - owslib
  - paegan
  - pandas
  - proj4
  - psutil
  - pygc
  - pykdtree
  - pyoos
  - pyproj
  - pyresample
  - pysgrid
  - pytest
  - pyugrid
  - pyyaml
  - qrcode
  - rasterio
  - rasterstats
  - requests
  - rios
  - rtree
  - scikit-learn
  - scipy
  - seaborn
  - seawater
  - shapely
  - siphon
  - spyder
  - statsmodels
  - sympy
  - thredds_crawler
  - utide
  - xarray
  - xlrd
  # R packages.
  - r-dt
  - r-ggfortify
  - r-ggplot2
  - r-gsw
  - r-httr
  - r-irkernel
  - r-lubridate
  - r-mapdata
  - r-ncdf4
  - r-oce
  - r-rcolorbrewer
  - r-reshape2
  - r-sp
  - r-xtractomatic
  - r-xts
  - pip:
    - ioos_tools
