name: IOOS
channels:
    - conda-forge
    - ioos
dependencies:
    - python=3.5
    - anaconda-navigator
    - beautifulsoup4
    - cartopy
    #- cc-plugin-glider  # Python 2.7
    - cmocean
    - compliance-checker
    - ctd
    - cython
    - descartes
    - fiona
    - folium
    - gdal
    - geojson
    - geojsonio
    - geopandas
    - geos
    - gridgeo
    - gsw
    - iris
    - jupyter
    - matplotlib
    - mpld3
    - mplleaflet
    - nb_conda_kernels
    - netcdf4
    - numpy
    - oceans
    - oct2py
    - owslib
    - paegan
    - pandas
    - proj.4
    - pygc
    - pykdtree
    - pyoos
    - pyproj
    - pyresample
    - pysgrid
    - pyugrid
    - pyyaml
    - qrcode
    - rasterio
    - rasterstats
    - requests
    - rios
    - rtree
    - scikit-learn
    - scipy
    - seaborn
    - seawater
    - shapely
    - siphon
    - spyder
    - statsmodels
    - sympy
    - thredds_crawler
    - utilities
    - xarray
    - xlrd
