name: IOOS
channels:
  - conda-forge
dependencies:
  - python=3.9
  - bagit
  - bokeh
  - cartopy
  - cc-plugin-glider
  - cc-plugin-ncei
  - cftime
  - compliance-checker
  - cython
  - descartes
  - easyargs
  - erddapy
  - flake8
  - folium
  - geojson
  - geojsonio
  - geolinks
  - geopandas
  - gridgeo
  - hvplot
  - ioos-tools
  - ioos_qc
  - ipyleaflet
  - joblib
  - jupyter
  - jupyter_contrib_nbextensions
  - jupyter_nbextensions_configurator
  - matplotlib-base
  - nbdime
  - nbval
  - nc-time-axis
  - nco
  - oceans
  - oct2py
  - palettable
  - phantomjs
  - pocean-core
  - pyoos
  - pyresample
  - pysgrid
  - pytest
  - pyugrid
  - pyworms
  - rasterio
  - seaborn
  - selenium
  - sensorml2iso
  - siphon
  - sympy
  - thredds_crawler
  - tqdm
  - utide
  - windrose
  - xarray
  - xlrd
  - xmltodict
  # R packages.
  - rpy2
  - r-base=4
  - r-dt
  - r-finch
  - r-ggfortify
  - r-ggplot2
  - r-gsw
  - r-httr
  - r-irkernel
  - r-lubridate
  - r-mapdata
  - r-ncdf4
  - r-oce
  - r-obistools
  - r-rcolorbrewer
  - r-rerddap
  - r-reshape2
  - r-robis>=2.3.9
  - r-sp
  - r-xtractomatic
  - r-xts

